# Use the official Node.js image as base
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your React app will run on
EXPOSE 5054

# Start the React app
CMD ["npm", "start"]


