version: "3.9"

services:
  suggestion-db:
    image: suggestion-box-db
    container_name: ci-suggestions-db
    ports:
      - '3306:3306'
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${DB_NAME}
    expose:
      - "3306"

  suggestions-backend:
    image: suggestion-box-backend
    container_name: ci-suggestions-backend
    ports:
      - '5055:5055'
    depends_on:
      - suggestion-db
    environment:
      DB_HOST: suggestion-db
      DB_PORT: 3306
      PORT: 5055
    expose:
      - "3001"

  suggestions-frontend:
    image: suggestion-box-frontend
    container_name: ci-suggestions-frontend
    ports:
      - '5054:5054'
    depends_on:
      - suggestions-backend
    environment:
      REACT_APP_BACKEND_URL: http://suggestions-backend:5055
      PORT: 5054
    expose:
      - "5054"
