version: '3'
services:
  suggestions-frontend:
    container_name: suggestions-frontend
    image: zfranke/suggestions-frontend
    ports:
      - '5055:5055'  
    networks:
      - suggestion-network

  suggestions-backend:
    container_name: suggestions-backend
    image: zfranke/suggestions-backend
    ports:
      - '5054:5054'  
    networks:
      - suggestion-network
    depends_on:
      - suggestion-db

  suggestion-db:
    container_name: suggestion-db
    image: zfranke/suggestions-db
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - suggestion-network

networks:
  suggestion-network:
    driver: bridge

volumes:
  db-data:
