version: '3'
services:
  suggestions-frontend:
    container_name: suggestions-frontend
    image: suggestions-frontend
    ports:
      - '5054:5054'  
    networks:
      - suggestions

  suggestions-backend:
    container_name: suggestions-backend
    image: suggestions-backend
    ports:
      - '5055:5055'  
    networks:
      - suggestions
    depends_on:
      - suggestion-db

  suggestion-db:
    container_name: suggestion-db
    image: suggestions-db
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - suggestions

networks:
  suggestions:
    external: true
    ipam:
      driver: default

volumes:
  db-data:
