version: "3.9"

services:
  suggestion-db:
    image: suggestion-box-db
    container_name: suggestion-db
    ports:
      - '3306:3306'
    networks: 
      - zf-network
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${DB_NAME}
    expose:
      - "3306"

  suggestions-backend:
    image: suggestion-box-backend
    container_name: suggestions-backend
    ports:
      - '5055:5055'
    depends_on:
      - suggestion-db
    networks:
      - zf-network
    environment:
      DB_HOST: suggestion-db
      DB_PORT: 3306
      PORT: 5055
    expose:
      - "3001"

  suggestions-frontend:
    image: suggestion-box-frontend
    container_name: suggestions-frontend
    ports:
      - '5054:5054'
    depends_on:
      - suggestions-backend
    networks:
      - zf-network
    environment:
      - REACT_APP_BACKEND_URL=http://suggestions-backend.zfserver.lan:5055
      - REACT_APP_FRONTEND_URL=http://suggestions.zfserver.lan
      - PORT=5054
    expose:
      - "5054"

networks:
   zf-network:
    external: true