# Stage 1: Build the application
FROM node:16 AS build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Stage 2: Create the production image
FROM node:16

WORKDIR /app

# Copy built application from the "build" stage
COPY --from=build /app .

# Expose the port your backend server is listening on
EXPOSE 5055

# Start the backend server
CMD ["node", "index.js"]
