# Use the official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=rootSuggestions79
ENV MYSQL_DATABASE=suggestion_box
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=suggestionsAreCool12

# Copy initialization SQL script
COPY init.sql /docker-entrypoint-initdb.d/
